AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Type: String
    Default: MyCloudFormationProject
  Env:
    Type: String
    Default: dev
  BackendDockerImage:
    Type: String
    Default: hungtran679/dkhp_demo-backend-service:ecs
  FrontendDockerImage:
    Type: String
    Default: hungtran679/dkhp_demo-frontend-service:ecs
  BackendPort:
    Type: Number
    Default: 8080
  FrontendPort:
    Type: Number
    Default: 80
Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cloudformation-antifact-bucket/616f05fa5dde6e266292b10f49388749.template
      Parameters:
        ProjectName:
          Ref: ProjectName
        Env:
          Ref: Env
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cloudformation-antifact-bucket/61613de3abf0bed1baff9c4f5636ed83.template
      Parameters:
        ProjectName:
          Ref: ProjectName
        Env:
          Ref: Env
        VpcId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.VpcId
        BackendPort:
          Ref: BackendPort
        FrontendPort:
          Ref: FrontendPort
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cloudformation-antifact-bucket/57d8a1feba2a04d808e935bf788c9fb8.template
      Parameters:
        ProjectName:
          Ref: ProjectName
        Env:
          Ref: Env
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cloudformation-antifact-bucket/9cb5a3520a26a3154f79c7e707a7aba4.template
      Parameters:
        ProjectName:
          Ref: ProjectName
        Env:
          Ref: Env
        VpcId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.VpcId
        PublicSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PublicSubnetIds
        LoadBalancerSgId:
          Fn::GetAtt:
          - SecurityGroupStack
          - Outputs.LoadBalancerSgId
        BackendPort:
          Ref: BackendPort
        FrontendPort:
          Ref: FrontendPort
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cloudformation-antifact-bucket/5ca64ebca41d179e78daa1022e9577ba.template
      Parameters:
        ProjectName:
          Ref: ProjectName
        Env:
          Ref: Env
        PublicSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PublicSubnetIds
        Ec2BastionSgId:
          Fn::GetAtt:
          - SecurityGroupStack
          - Outputs.Ec2BastionSgId
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cloudformation-antifact-bucket/756954d81907d55cc37e797116e8cd8f.template
      Parameters:
        ProjectName:
          Ref: ProjectName
        Env:
          Ref: Env
        PrivateDataSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PrivateDataSubnetIds
        DatabaseSgId:
          Fn::GetAtt:
          - SecurityGroupStack
          - Outputs.DatabaseSgId
  EcsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cloudformation-antifact-bucket/54e0b687f3df094bdfe6065573bbd58a.template
      Parameters:
        ProjectName:
          Ref: ProjectName
        Env:
          Ref: Env
        BackendDockerImage:
          Ref: BackendDockerImage
        FrontendDockerImage:
          Ref: FrontendDockerImage
        BackendPort:
          Ref: BackendPort
        FrontendPort:
          Ref: FrontendPort
        VpcId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.VpcId
        PrivateAppSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PrivateAppSubnetIds
        EcsTaskRoleArn:
          Fn::GetAtt:
          - IamStack
          - Outputs.EcsTaskRoleArn
        EcsTaskExecutionRoleArn:
          Fn::GetAtt:
          - IamStack
          - Outputs.EcsTaskExecutionRoleArn
        EcsAutoScalingRoleArn:
          Fn::GetAtt:
          - IamStack
          - Outputs.EcsAutoScalingRoleArn
        BackendTargetGroupArn:
          Fn::GetAtt:
          - LoadBalancerStack
          - Outputs.BackendTargetGroupArn
        FrontendTargetGroupArn:
          Fn::GetAtt:
          - LoadBalancerStack
          - Outputs.FrontendTargetGroupArn
        EcsBackendServiceSgId:
          Fn::GetAtt:
          - SecurityGroupStack
          - Outputs.EcsBackendServiceSgId
        EcsFrontendServiceSgId:
          Fn::GetAtt:
          - SecurityGroupStack
          - Outputs.EcsFrontendServiceSgId
        DBCredentialSecretArn:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DBCredentialSecretArn
        JDBCConnectionString:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.JDBCConnectionString
