AWSTemplateFormatVersion: "2010-09-09"

#------------------------------------------------------
# Parameters
#------------------------------------------------------
Parameters:
  ProjectName:
    Type: String
  Env:
    Type: String
  
  PrivateDataSubnetIds:
    Type: String
  DatabaseSgId:
    Type: String
  
  DbUser:
    Description: The root database username
    Type: String
    Default: admin
  DbName:
    Description: The init database name
    Type: String
    Default: mydb
  DbAllocatedStorage:
    Description: The storage size of database
    Type: Number
    Default: 20
  DbInstanceClass:
    Description: The compute instance class of database
    Type: String
    Default: "db.t4g.micro"
  MultiAZ:
    Description: Multi-AZ master database
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "true"
  EnableReadReplica:
    Description: Enable the ReadReplica
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

#------------------------------------------------------
# Conditions
#------------------------------------------------------ 
Conditions:
  CreateReadReplica: !Equals [!Ref EnableReadReplica, "true"]

#------------------------------------------------------
# DB Resources
#------------------------------------------------------ 
Resources:
  #------------------------------------------------------
  # DB Subnet Groups
  #------------------------------------------------------ 
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "App DB Subnet Group"
      DBSubnetGroupName: !Sub "${ProjectName}-${Env}-db-subnet-group"
      SubnetIds: !Split [",", !Ref PrivateDataSubnetIds]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-db-subnet-group"
        - Key: Environment
          Value: !Ref Env
  
  #------------------------------------------------------
  # DB Root Password Credential
  #------------------------------------------------------ 
  DBCredential:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${ProjectName}-${Env}-db-password-secret"
      GenerateSecretString:
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-db-password-secret"
        - Key: Environment
          Value: !Ref Env
  
  #------------------------------------------------------
  # DB Intances
  #------------------------------------------------------ 
  MainDB:
    Type: AWS::RDS::DBInstance
    # DeletionPolicy: Snapshot
    # UpdateReplacePolicy: Snapshot
    DependsOn: DBCredential
    Properties:
      DBInstanceIdentifier: !Sub "${ProjectName}-${Env}-main-rds-db"
      DBName: !Ref DbName
      AllocatedStorage: !Ref DbAllocatedStorage
      BackupRetentionPeriod: 7
      DBInstanceClass: !Ref DbInstanceClass
      DBSubnetGroupName: !Ref DbSubnetGroup
      Engine: mysql
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBCredential}}}'
      MultiAZ: !Ref MultiAZ
      PubliclyAccessible: false
      StorageEncrypted: true
      VPCSecurityGroups:
        - !Ref DatabaseSgId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-main-rds-db"
        - Key: Environment
          Value: !Ref Env

  ReplicaDB:
    Type: AWS::RDS::DBInstance
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Condition: CreateReadReplica
    Properties:
      SourceDBInstanceIdentifier: !Ref MainDB
      PubliclyAccessible: false
      DBInstanceClass: !Ref DbInstanceClass
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-replica-rds-db"
        - Key: Environment
          Value: !Ref Env

#------------------------------------------------------
# Outputs 
#------------------------------------------------------
Outputs:
  DBCredentialSecretArn:
    Description: Name of the secret containing the database credential
    Value: !Ref DBCredential
  JDBCConnectionString:
    Description: JDBC connection string for the master database
    Value: !Join
      - ""
      - - jdbc:mysql://
        - !GetAtt MainDB.Endpoint.Address
        - ':'
        - !GetAtt MainDB.Endpoint.Port
        - /
        - !Ref DbName
  ReplicaJDBCConnectionString:
    Description: JDBC connection string for the replica database
    Value: !Join
      - ""
      - - jdbc:mysql://
        - !GetAtt ReplicaDB.Endpoint.Address
        - ':'
        - !GetAtt ReplicaDB.Endpoint.Port
        - /
        - !Ref DbName
    Condition: CreateReadReplica
